name: main_workflow
on:
  push:
    branches:
      - Bingo_Workflow
jobs:
  syntax_check_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Linter execution
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: Bingo_Workflow
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          VALIDATE_JAVASCRIPT_ES: true
  test_execution_job:
    runs-on: ubuntu-latest
    steps:
    - name: Check Tests
      run: npm install; npm test



          
  #  test_execution_job:
  #  runs-on: ubuntu-latest
  #  steps:
  #   - name: Check tests
  #     uses: 
